### ISSUE TITLE
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096]

### ISSUE THREAD

**Issue by hadign20** [CharlesShang/TFFRCNN#68]
I am trying to perform faster rcnn on a custom dataset based on pascal_VOC. But I get this error when I start to train:

Stats: 
Limit:                  1696386252
InUse:                  1685909760
MaxInUse:               1696386048
NumAllocs:                     152
MaxAllocSize:            533417472

2017-06-03 04:51:48.992694: W tensorflow/core/common_runtime/bfc_allocator.cc:277] *********************************************************************************************xxxxxxx
2017-06-03 04:51:48.992751: W tensorflow/core/framework/op_kernel.cc:1152] Resource exhausted: OOM when allocating tensor with shape[25088,4096]
Traceback (most recent call last):
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 148, in train_model
    sess.run(tf.global_variables_initializer())
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[4096]
	 [[Node: fc6/biases/Momentum/Assign = Assign[T=DT_FLOAT, _class=["loc:@fc6/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fc6/biases/Momentum, fc6/biases/Momentum/Initializer/Const)]]

Caused by op u'fc6/biases/Momentum/Assign', defined at:
  File "./faster_rcnn/train_net.py", line 109, in <module>
    restore=bool(int(args.restore)))
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 400, in train_net
    sw.train_model(sess, max_iters, restore=restore)
  File "./faster_rcnn/../lib/fast_rcnn/train.py", line 143, in train_model
    train_op = opt.apply_gradients(zip(grads, tvars), global_step=global_step)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/momentum.py", line 63, in _create_slots
    self._zeros_slot(v, "momentum", self._name)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1049, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 948, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 356, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 341, in _true_getter
    use_resource=use_resource)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 714, in _get_single_variable
    validate_shape=validate_shape)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 197, in __init__
    expected_shape=expected_shape)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 306, in _init_from_args
    validate_shape=validate_shape).op
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/hadi/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096]
	 [[Node: fc6/biases/Momentum/Assign = Assign[T=DT_FLOAT, _class=["loc:@fc6/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fc6/biases/Momentum, fc6/biases/Momentum/Initializer/Const)]]`

How can I make this work? I don't know how to reduce batch size and see if that helps.

**Comment by Asiapenolove** [comment]
take a look at the memory usage of your gpu with
```
nvidia-smi -l 3
```
if still free memory that can be used 
-> edit  lib/fast_rcnn/train.py
~line396 : config.gpu_options.per_process_gpu_memory_fraction = 0.40 
edit 0.40 to larger propotion (e.g. 0.9)

**Comment by AuroraLHT** [comment]
to keep an eye on the GPU usage:
`sudo watch mvidia-smi`

you can twist the source code for expending gpu memory usage:
try modify the parameters on the line below in TFFRCNN/lib/fast_rcnn/train.py
```python
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.allocator_type = 'BFC'
config.gpu_options.per_process_gpu_memory_fraction = 0.40
```

`config.gpu_options.allow_growth=True` is always my favored option since you don't need to care about the actual usage.

**Comment by LMdeLiangMi** [comment]
same problem
I try to add config.gpu_options.allow_growth=True but it still ResourceExhausted...
how to fix this? my gpu is gtx 950m

2017-07-02 14:08:35.353748: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-07-02 14:08:35.353994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 0.928
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.67GiB

**Comment by LinkToPast1990** [comment]
same problem
I add config.gpu_options.allow_growth=True but it still ResourceExhausted...
how to fix this? my gpu is gtx 950m

2017-07-02 14:08:35.353748: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-07-02 14:08:35.353994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties:
name: GeForce GTX 950M
major: 5 minor: 0 memoryClockRate (GHz) 0.928
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.67GiB

**Comment by LinkToPast1990** [comment]
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[25088,4096]
	 [[Node: gradients/fc6/fc6/MatMul_grad/MatMul_1 = MatMul[T=DT_FLOAT, transpose_a=true, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](fc6/Reshape, gradients/fc6/fc6_grad/ReluGrad)]]
	 [[Node: Momentum/update/_204 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1822_Momentum/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by LinkToPast1990** [comment]
def train_net(network, imdb, roidb, output_dir, log_dir, pretrained_model=None, max_iters=40000, restore=False):
    """Train a Fast R-CNN network."""

    config = tf.ConfigProto(allow_soft_placement=True)
    config.gpu_options.allocator_type = 'BFC'
    #config.gpu_options.per_process_gpu_memory_fraction = 0.40
    config.gpu_options.allow_growth = True

**Comment by AuroraLHT** [comment]
@LMdeLiangMi 
Try this. 3.95GB * 0.8 would provide 3.16 GB memory for allocation, which meets the minimum requirement of GPU free memory.
```
    config = tf.ConfigProto(allow_soft_placement=True)
    config.gpu_options.allocator_type = 'BFC'
    config.gpu_options.per_process_gpu_memory_fraction = 0.80
```

**Comment by LinkToPast1990** [comment]
Thanks
Should I use something like batch generator to avoid out of memory of gpu or ram？

可以使用 tensorflow 提供的 batch generator, 首先把数据送入队列中 queue, 然后需要一种 tensorflow reader （tf 有好几种reader), 然后从队列中读取数据, 然后使用 tf.train.batch 或者 tf.train.shuffle_batch 就可以生成你定义的 batch size 的数据了，需要用 Coordinator()和 start_queue_runner 监控队列的状态。

**Comment by LinkToPast1990** [comment]
What is bfc？

**Comment by LinkToPast1990** [comment]
@AuroraLHT  Sad...3.95GB * 0.8, same problem...

**Comment by AuroraLHT** [comment]
@LMdeLiangMi to use batch_generator, first you need to convert your raw input into a specific file via TFRecordWriter. In this implement, the batch number is always to be 1, meaning that it is unnecessary to use batch_generator.

**Comment by LinkToPast1990** [comment]
@AuroraLHT  I think maybe this implement just read all the data at one time so out of memory.
But it seems to happen when computing？’‘OOM when allocating tensor with shape[25088,4096]’‘

**Comment by LinkToPast1990** [comment]
https://stackoverflow.com/questions/39076388/tensorflow-deep-mnist-resource-exhausted-oom-when-allocating-tensor-with-shape

**Comment by AuroraLHT** [comment]
@LMdeLiangMi Check TFFRCNN/lib/roi_data_layer/layer.py. It provides some insights of imdb's mechanism. Hope it could help. 
[BTW, google research has release its own object detection API : ](https://github.com/tensorflow/models/tree/master/object_detection) 
Try google's api if you can't solve the memory problem.

**Comment by LinkToPast1990** [comment]
@AuroraLHT Thanks......But I really want to solve this memory problem
1、Tensorflow Minist Example
step 19900, training accuracy 1
2017-07-02 15:57:33.230281: W tensorflow/core/common_runtime/http://bfc_allocator.cc:217]
 Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.59GiB. The
 caller indicates that this is not a failure, but may mean that there 
could be performance gains if more memory is available.
2017-07-02 15:57:34.382333: W tensorflow/core/common_runtime/http://bfc_allocator.cc:217]
 Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.90GiB. The
 caller indicates that this is not a failure, but may mean that there 
could be performance gains if more memory is available.
test accuracy 0.9919

2、Faster RCNN
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[4096] · Issue #68 · CharlesShang/TFFRCNN

**Comment by LinkToPast1990** [comment]
Fix! Using beneth setting!
Start train now!
Iter 450/70000(may need couple hours)
config = tf.ConfigProto()
config.gpu_options.allocator_type ='BFC'
config.gpu_options.per_process_gpu_memory_fraction = 0.90

**Comment by rolla12** [comment]
TensorFlow Version: 1.4.1
2018-01-07 11:53:14.284064: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-07 11:53:14.284554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1050 major: 6 minor: 1 memoryClockRate(GHz): 1.493
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.54GiB
...
Limit:                  1420754944
InUse:                  1419662336
MaxInUse:               1419662336
NumAllocs:                     124
MaxAllocSize:            819144192

2018-01-07 11:53:57.823764: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ************************************************************************xxxxxxxxxxxxxxxxxxxxxxxxxxxx
2018-01-07 11:53:57.823816: W tensorflow/core/framework/op_kernel.cc:1182] Resource exhausted: OOM when allocating tensor of shape [1,1,4096,4096] and type float
2018-01-07 11:53:57.874319: E tensorflow/core/common_runtime/executor.cc:643] Executor failed to create kernel. Resource exhausted: OOM when allocating tensor of shape [1,1,4096,4096] and type float

## ### 
**_### **# i got the same issue when i was trying to train cnn using pertained vgg-16  ********_
how can i force it to use one gpu or to be run on cpu ..do i need to install TF for cpu???

**Comment by gxx101** [comment]
config = tf.ConfigProto()
config.gpu_options.allocator_type ='BFC'
config.gpu_options.per_process_gpu_memory_fraction = 0.90
where does it need to set up?

**Comment by gxx101** [comment]
config = tf.ConfigProto() ，what is 'tf'?tensorflow?

**Comment by Yue-Rain** [comment]
@gxx101 yes,"tf" is tensorflow.you can add config as a parameter passed to `tf.Session()` just as`with tf.Session(config=config) as sess:` do.

**Comment by Ashish1997** [comment]
I got a similar error and it got resolved by reducing the batch_size.

**Comment by chrenlily** [comment]
@LMdeLiangMi ,I got a similar error and setted config.gpu_options.per_process_gpu_memory_fraction = 0.90,but it still don't solve the probblem.could you give me some advice

**Comment by chrenlily** [comment]
@LMdeLiangMi ,I got a similar error and setted
 config.gpu_options.per_process_gpu_memory_fraction = 0.90,
but it still don't solve the problem.could you give me some advice

**Comment by Ashish1997** [comment]
I was using tensorflow API for training FRCNN on custom data and my GPU
config is NVIDIA 1050, 4GB which is not sufficient.
If your batch size is even 30 then also it will show OOM error.
To FIX THIS I TURNED OFF GPU and trained on CPU.
If your GPU more then 4GB you can play with batch size to so that it can
fit on GPU else use CPU for training

**Comment by AndiDemon** [comment]
I had problem like this, I am using NVIDIA GeForce GTX 1080 8 gb.
The problem is with the data that I input around 7000 of float array data, the exact same error like @hadi-ghnd has shown.
After trying to limit the data through the model, it worked fine.
the max limit of data that I found was around 3000 of float array data.
I think it depends on your GPU memory.
